### ISSUE TITLE
Coleção do Postman

### ISSUE THREAD

**Issue by msmagnanijr** [ezambomsantana/livro-kafka#1]
Fala Eduardo tudo bem?

Não sei se deixei passar algo mas não encontrei a coleção (postman) referida no cap1 para realização dos testes a partir do cap3. Isso está mesmo disponível aqui nesse repo?

Obrigado :)

**Comment by ezambomsantana** [comment]
Olá Mauricio, desculpe a demora e obrigado pelo comentário, realmente esqueci de subir o arquivo.

 Adicionei a collection do Postman na raiz do projeto.
